Repository ToucanToco/camouflage, pull requests merged in 2019-12, with the labels that each got.

#248 Bulletchart :: Change color usage to improve clarity
  new-charts/tc-bulletchart.scss
Labels: feature

#249 Add color for loading bar
  slide/additional-panel.scss
Labels: feature

#250 Charts :: Change the bulletchart's layout to a table
  colors.scss
  embed.scss
  main.scss
  new-charts/components/axis-bottom.scss
  new-charts/components/components.scss
  new-charts/tc-bullet-chart.scss
  new-charts/tc-bulletchart.scss
  new-charts/tc-charts.scss
Labels: feature

#252 Colors for mobile additional infos
  main.scss
  slide/mobile-additional-infos.scss
Labels: feature

#253 Additional Panel :: rename share as share-tab
  slide/additional-panel.scss
Labels: tech

#255 Additional panel :: polishing - update colors
  slide/additional-panel.scss
  small-app/component/comments/comments.scss
Labels: to merge

#251 Hotfix :: Table Chart :: Values should have a pretty size
  new-charts/tc-tablechart.scss
Labels: bug
