Repository ToucanToco/camouflage, pull requests merged in 2020-03, with the labels that each got.

#264 Studio :: Add loop and variables to use series colors interface
  new-charts/color-elements.scss
  variables.scss
Labels: feature

#266 Additional Panel :: add background to improve ux on transitions
  slide/additional-panel.scss
Labels: feature, to merge

#267 Charts :: Fix series colors mixin
  new-charts/color-elements.scss
  new-charts/tc-linechart.scss
Labels: bug, to merge

#265 Charts :: Add a new Metas component
  new-charts/components/components.scss
  new-charts/components/details.scss
  new-charts/components/metas.scss
  new-charts/components/serie.scss
Labels: feature, to merge

#268 Linechart (old) :: Give a higher priority to the data-serie rules
  new-charts/color-elements.scss
Labels: bug

#269 Replace font-awesome with svg for search icon (except studio)
  charts/mapchart.scss
Labels: feature, to merge

#270 Fix :: Set input type range background based on custom smallApp variables
  new-charts/components/slider-filter.scss
Labels: tech

#271 Fix:: Unstackable declarations for input type slider
  new-charts/components/slider-filter.scss
Labels: bug
