Repository ToucanToco/camouflage, pull requests merged in 2020-05, with the labels that each got.

#287 Bullet :: Add similar color for chart and tile
  new-charts/graphical-elements/graphical-elements.scss
  new-charts/graphical-elements/horizontal-bar-with-bullet.scss
  new-charts/tc-bullet-chart.scss
  new-charts/tc-details.scss
  new-charts/tc-legend/tc-legend-ordinal.scss
  variables.scss
Labels: bug, cleaning, to merge

#288 Bullet :: Allow custom colors series
  new-charts/color-elements.scss
  new-charts/tc-bullet-chart.scss
  variables.scss
Labels: feature

#290 Monaco editor :: fix search bar
  variables.scss
Labels: bug

#291 Buttons :: Fix :: Buttons should not be selectable
  buttons.scss
Labels: bug, to merge
