Repository ToucanToco/camouflage, pull requests merged in 2020-04, with the labels that each got.

#272 Colors :: Add index key to colors array
  charts.scss
  charts/bullet-chart.scss
  charts/force-directed-chart.scss
  charts/leaderboard.scss
  charts/waterfall.scss
  dashboard-report.scss
  new-charts/graphical-elements/bullet.scss
  new-charts/graphical-elements/horizontal-bar-with-bullet.scss
  new-charts/tc-barchart.scss
  new-charts/tc-bubblechart.scss
  new-charts/tc-details.scss
  new-charts/tc-horizontal-barchart.scss
  new-charts/tc-legend/tc-legend-ordinal.scss
  new-charts/tc-legend/tc-legend-quantile.scss
  new-charts/tc-linechart.scss
  new-charts/tc-lines.scss
  new-charts/tc-map.scss
  new-charts/tc-mapchart.scss
  new-charts/tc-radarchart.scss
  new-charts/tc-stackedbarchart.scss
  new-charts/tc-tablechart.scss
  new-charts/tc-versuschart.scss
  pane-details.scss
  sparklines.scss
  variables.scss
Labels: bug, cleaning

#273 Cleaning :: Remove reference to Carto & Filtrable-waterfall
  new-charts/color-elements.scss
Labels: cleaning

#274 Remove bulletchart elements backgrounds
  new-charts/tc-bullet-chart.scss
Labels: bug

#275 Chart Colors :: Fix index off by one error
  charts/bullet-chart.scss
  dashboard-report.scss
  new-charts/graphical-elements/bullet.scss
  new-charts/graphical-elements/horizontal-bar-with-bullet.scss
  sparklines.scss
  variables.scss
Labels: bug

#276 TableChart :: Add mixin to custom colors with color scheme interface
  new-charts/color-elements.scss
  new-charts/tc-tablechart.scss
Labels: feature

#278 Tutorial :: fix var name
  small-app-tutorial.scss
Labels: bug

#279 Story :: Change commentary mobile classes
  slide/mobile-additional-infos.scss
Labels: feature

#282 Fix :: fix funnelchart bar colors
  new-charts/tc-charts.scss
  new-charts/tc-funnelchart.scss
Labels: bug

#283 Fix :: Use variable for funnelchart bar colors
  new-charts/tc-funnelchart.scss
  variables.scss
Labels: bug

#280 Linechart :: Implement showValues
  new-charts/tc-linechart.scss
Labels: feature

#285 Linechart :: Move sentiment colors from tucana to camouflage
  new-charts/tc-linechart.scss
Labels: bug

#284 [compact-mode] :: remove responsive buttons font-size from camouflage
  variables.scss
Labels: tech

#286 [compact-mode] :: DropdownFilter
  utils/components/tc-dropdown.scss
Labels: tech
